import { type FormEvent, useEffect, useState } from "react";
import type { CatalogBranch, CatalogCopy, CatalogSearchItem, CatalogSearchResult, CatalogShelf, CatalogTitleDraft } from "../../domain/catalog";
import { useServices } from "../app/services-context";
import { DataTable } from "../components/data-table";
import { FormField } from "../components/form-field";
import { StatusBadge } from "../components/status-badge";
import { Toast } from "../components/toast";

const emptyTitle: CatalogTitleDraft = { title:"",isbn:"",authorsText:"",subjectsText:"",publisher:"" };

export function CatalogPage() {
  const services=useServices();
  const [tab,setTab]=useState<"search"|"titles"|"copies"|"locations">("search");
  const [branches,setBranches]=useState<CatalogBranch[]>([]);
  const [shelves,setShelves]=useState<CatalogShelf[]>([]);
  const [copies,setCopies]=useState<CatalogCopy[]>([]);
  const [query,setQuery]=useState(""); const [filterBranch,setFilterBranch]=useState("");
  const [result,setResult]=useState<CatalogSearchResult|null>(null);
  const [active,setActive]=useState<CatalogSearchItem|null>(null);
  const [titleDraft,setTitleDraft]=useState<CatalogTitleDraft>(emptyTitle);
  const [copyDraft,setCopyDraft]=useState({branchId:"",shelfLocationId:"",barcode:"",rfid:""});
  const [selectedCopy,setSelectedCopy]=useState<CatalogCopy|null>(null);
  const [locationBranch,setLocationBranch]=useState("");
  const [branchDraft,setBranchDraft]=useState({code:"",name:"",address:""});
  const [shelfDraft,setShelfDraft]=useState({code:"",label:""});
  const [pending,setPending]=useState(false); const [error,setError]=useState(""); const [message,setMessage]=useState("");

  useEffect(()=>{services.listCatalogBranches.execute().then(setBranches).catch((e)=>setError(e instanceof Error?e.message:"Không tải được chi nhánh"));},[services]);
  const run=async<T,>(work:()=>Promise<T>)=>{setPending(true);setError("");setMessage("");try{return await work();}catch(e){setError(e instanceof Error?e.message:"Thao tác thất bại");return null;}finally{setPending(false);}};
  async function search(page=1){const data=await run(()=>services.searchCatalog.execute({query,branchId:filterBranch||undefined,page,limit:20}));if(data)setResult(data);}
  function chooseTitle(item:CatalogSearchItem){setActive(item);setTitleDraft({title:item.title,isbn:item.isbn||"",authorsText:item.authors.join(", "),subjectsText:item.subjects.join(", "),publisher:item.publisher||""});}
  async function saveTitle(e:FormEvent){e.preventDefault();const saved=active?await run(()=>services.updateCatalogTitle.execute(active.id,titleDraft)):await run(()=>services.createCatalogTitle.execute(titleDraft));if(saved){setActive({...saved,availability:active?.availability??[]});setMessage(`Đã lưu đầu sách ${saved.title}`);}}
  async function loadShelves(branchId:string){setCopyDraft(d=>({...d,branchId,shelfLocationId:""}));setLocationBranch(branchId);if(!branchId){setShelves([]);return;}const data=await run(()=>services.listCatalogShelves.execute(branchId));if(data)setShelves(data);}
  async function openCopies(){setTab("copies");if(active){const data=await run(()=>services.listCatalogCopies.execute(active.id));if(data)setCopies(data);}}
  async function saveCopy(e:FormEvent){e.preventDefault();if(!active)return;const draft={bookTitleId:active.id,...copyDraft};const saved=selectedCopy?await run(()=>services.updateCatalogCopy.execute(selectedCopy.id,draft)):await run(()=>services.createCatalogCopy.execute(draft));if(saved){setCopies(rows=>selectedCopy?rows.map(x=>x.id===saved.id?saved:x):[...rows,saved]);setSelectedCopy(null);setCopyDraft({branchId:"",shelfLocationId:"",barcode:"",rfid:""});setMessage(`Đã lưu bản sao ${saved.barcode}`);}}
  async function createBranch(e:FormEvent){e.preventDefault();const saved=await run(()=>services.createCatalogBranch.execute(branchDraft));if(saved){setBranches(rows=>[...rows,saved]);setLocationBranch(saved.id);setBranchDraft({code:"",name:"",address:""});setMessage(`Đã tạo chi nhánh ${saved.code}`);}}
  async function createShelf(e:FormEvent){e.preventDefault();const saved=await run(()=>services.createCatalogShelf.execute(locationBranch,shelfDraft));if(saved){setShelves(rows=>[...rows,saved]);setShelfDraft({code:"",label:""});setMessage(`Đã tạo kệ ${saved.code}`);}}

  return <section><div className="page-heading"><div><p className="eyebrow">Catalog</p><h1>Quản lý mục lục</h1></div></div>
    <div className="tabs"><button aria-label="Mở tab tìm kiếm" className={tab==="search"?"active":""} onClick={()=>setTab("search")}>Tìm kiếm</button><button className={tab==="titles"?"active":""} onClick={()=>setTab("titles")}>Đầu sách</button><button className={tab==="copies"?"active":""} onClick={()=>void openCopies()}>Bản sao</button><button className={tab==="locations"?"active":""} onClick={()=>setTab("locations")}>Chi nhánh & kệ</button></div>
    {active&&<div className="active-selection"><span>Đầu sách đang chọn</span><strong>{active.title}</strong><small>{active.id}</small></div>}
    {error&&<Toast message={error} tone="error"/>}{message&&<Toast message={message}/>} 
    {tab==="search"&&<><form className="panel form-grid" onSubmit={(e)=>{e.preventDefault();void search();}}><FormField label="Từ khóa"><input value={query} onChange={e=>setQuery(e.target.value)}/></FormField><FormField label="Lọc chi nhánh"><select value={filterBranch} onChange={e=>setFilterBranch(e.target.value)}><option value="">Tất cả</option>{branches.map(b=><option key={b.id} value={b.id}>{b.code} · {b.name}</option>)}</select></FormField><div className="form-actions"><button disabled={pending}>Tìm kiếm</button></div></form>
      {result&&<>{result.items.length===0?<p className="state-panel">Không tìm thấy đầu sách.</p>:<div className="catalog-results">{result.items.map(item=><article className="catalog-card" key={item.id}><div><h2>{item.title}</h2><p>{item.authors.join(", ")}</p><small>{item.isbn||"Không ISBN"} · {item.publisher||"Không NXB"}</small><p>{item.availability.map(a=>`${a.branchId}: ${a.availableCopies}`).join(" · ")||"Chưa có bản sao"}</p></div><button aria-label={`Chọn ${item.title}`} onClick={()=>chooseTitle(item)}>Chọn</button></article>)}</div>}<div className="pagination"><button className="button-secondary" disabled={pending||result.meta.page<=1} onClick={()=>void search(result.meta.page-1)}>Trang trước</button><span>Trang {result.meta.page}/{result.meta.totalPages||1}</span><button className="button-secondary" disabled={pending||result.meta.page>=result.meta.totalPages} onClick={()=>void search(result.meta.page+1)}>Trang sau</button></div></>}</>}
    {tab==="titles"&&<form className="panel form-grid" onSubmit={saveTitle}><FormField label="Tên sách"><input value={titleDraft.title} onChange={e=>setTitleDraft({...titleDraft,title:e.target.value})}/></FormField><FormField label="ISBN"><input value={titleDraft.isbn} onChange={e=>setTitleDraft({...titleDraft,isbn:e.target.value})}/></FormField><FormField label="Tác giả"><textarea value={titleDraft.authorsText} onChange={e=>setTitleDraft({...titleDraft,authorsText:e.target.value})}/></FormField><FormField label="Chủ đề"><textarea value={titleDraft.subjectsText} onChange={e=>setTitleDraft({...titleDraft,subjectsText:e.target.value})}/></FormField><FormField label="Nhà xuất bản"><input value={titleDraft.publisher} onChange={e=>setTitleDraft({...titleDraft,publisher:e.target.value})}/></FormField><div className="form-actions">{active&&<button type="button" className="button-secondary" onClick={()=>{setActive(null);setTitleDraft(emptyTitle);}}>Tạo mới</button>}<button disabled={pending}>{active?"Cập nhật đầu sách":"Tạo đầu sách"}</button></div></form>}
    {tab==="copies"&&(!active?<p className="state-panel">Chọn một đầu sách từ kết quả tìm kiếm trước.</p>:<><form className="panel form-grid" onSubmit={saveCopy}><FormField label="Chi nhánh bản sao"><select value={copyDraft.branchId} onChange={e=>void loadShelves(e.target.value)}><option value="">Chọn chi nhánh</option>{branches.map(b=><option key={b.id} value={b.id}>{b.code} · {b.name}</option>)}</select></FormField><FormField label="Kệ bản sao"><select value={copyDraft.shelfLocationId} onChange={e=>setCopyDraft({...copyDraft,shelfLocationId:e.target.value})}><option value="">Chọn kệ</option>{shelves.map(s=><option key={s.id} value={s.id}>{s.code} · {s.label}</option>)}</select></FormField><FormField label="Barcode"><input value={copyDraft.barcode} onChange={e=>setCopyDraft({...copyDraft,barcode:e.target.value})}/></FormField><FormField label="RFID"><input value={copyDraft.rfid} onChange={e=>setCopyDraft({...copyDraft,rfid:e.target.value})}/></FormField><div className="form-actions"><button disabled={pending}>{selectedCopy?"Cập nhật bản sao":"Tạo bản sao"}</button></div></form>{copies.length>0&&<DataTable rows={copies} rowKey={x=>x.id} columns={[{key:"barcode",header:"Barcode",render:x=>x.barcode},{key:"location",header:"Vị trí",render:x=>`${x.branchId} / ${x.shelfLocationId}`},{key:"status",header:"Trạng thái",render:x=><StatusBadge value={x.status}/>},{key:"action",header:"",render:x=><button className="button-link" onClick={()=>{setSelectedCopy(x);setCopyDraft({branchId:x.branchId,shelfLocationId:x.shelfLocationId,barcode:x.barcode,rfid:x.rfid||""});}}>Sửa</button>}]} />}</>)}
    {tab==="locations"&&<div className="two-column"><form className="panel" onSubmit={createBranch}><h2>Tạo chi nhánh</h2><FormField label="Mã chi nhánh"><input value={branchDraft.code} onChange={e=>setBranchDraft({...branchDraft,code:e.target.value})}/></FormField><FormField label="Tên chi nhánh"><input value={branchDraft.name} onChange={e=>setBranchDraft({...branchDraft,name:e.target.value})}/></FormField><FormField label="Địa chỉ"><input value={branchDraft.address} onChange={e=>setBranchDraft({...branchDraft,address:e.target.value})}/></FormField><button disabled={pending}>Tạo chi nhánh</button></form><form className="panel" onSubmit={createShelf}><h2>Tạo kệ</h2><FormField label="Chi nhánh của kệ"><select value={locationBranch} onChange={e=>void loadShelves(e.target.value)}><option value="">Chọn chi nhánh</option>{branches.map(b=><option key={b.id} value={b.id}>{b.code} · {b.name}</option>)}</select></FormField><FormField label="Mã kệ"><input value={shelfDraft.code} onChange={e=>setShelfDraft({...shelfDraft,code:e.target.value})}/></FormField><FormField label="Nhãn kệ"><input value={shelfDraft.label} onChange={e=>setShelfDraft({...shelfDraft,label:e.target.value})}/></FormField><button disabled={pending}>Tạo kệ</button>{shelves.length>0&&<ul className="compact-list">{shelves.map(s=><li key={s.id}><strong>{s.code}</strong> {s.label}</li>)}</ul>}</form></div>}
  </section>;
}
