import { type FormEvent, useState } from "react";
import type { InventoryScan, InventorySession } from "../../domain/operations";
import { useServices } from "../app/services-context";
import { FormField } from "../components/form-field";
import { StatusBadge } from "../components/status-badge";
import { Toast } from "../components/toast";

export function InventoryPage() {
  const s=useServices(); const[branchId,setBranchId]=useState("");const[shelfId,setShelfId]=useState("");const[session,setSession]=useState<InventorySession|null>(null);const[barcode,setBarcode]=useState("");const[scans,setScans]=useState<InventoryScan[]>([]);const[statusBarcode,setStatusBarcode]=useState("");const[status,setStatus]=useState("DAMAGED");const[reason,setReason]=useState("");const[msg,setMsg]=useState("");const[error,setError]=useState("");
  const run=async<T,>(fn:()=>Promise<T>)=>{setError("");try{return await fn();}catch(e){setError(e instanceof Error?e.message:"Thao tác thất bại");return null;}};
  async function create(e:FormEvent){e.preventDefault();const x=await run(()=>s.createInventory.execute(branchId,shelfId));if(x){setSession(x);setScans([]);setMsg("Đã tạo phiên kiểm kê");}}
  async function scan(e:FormEvent){e.preventDefault();if(!session)return;const x=await run(()=>s.scanInventory.execute(session.id,barcode));if(x){setScans(v=>[x,...v]);setBarcode("");}}
  async function complete(){if(!session)return;const x=await run(()=>s.completeInventory.execute(session.id));if(x){setSession(x);setMsg(`Đã chốt kiểm kê, thiếu ${x.missingCount??0} bản sao`);}}
  async function change(e:FormEvent){e.preventDefault();const x=await run(()=>s.updateCopyCondition.execute(statusBarcode,status,reason));if(x){setMsg(`Đã cập nhật ${x.barcode} thành ${x.status}`);setReason("");}}
  return <section><div className="page-heading"><div><p className="eyebrow">Inventory</p><h1>Kiểm kê và tình trạng sách</h1></div></div>{error&&<Toast message={error} tone="error"/>}{msg&&<Toast message={msg}/>}<div className="two-column"><form className="panel" onSubmit={create}><h2>Tạo phiên kiểm kê</h2><FormField label="ID chi nhánh"><input value={branchId} onChange={e=>setBranchId(e.target.value)}/></FormField><FormField label="ID kệ (không bắt buộc)"><input value={shelfId} onChange={e=>setShelfId(e.target.value)}/></FormField><button>Tạo phiên</button></form><form className="panel" onSubmit={change}><h2>Mất / hỏng / thanh lý</h2><FormField label="Mã bản sao"><input value={statusBarcode} onChange={e=>setStatusBarcode(e.target.value)}/></FormField><FormField label="Trạng thái"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="DAMAGED">Hư hỏng</option><option value="LOST">Thất lạc</option><option value="WITHDRAWN">Thanh lý</option></select></FormField><FormField label="Lý do"><input value={reason} onChange={e=>setReason(e.target.value)}/></FormField><button>Cập nhật trạng thái</button></form></div>{session&&<article className="panel"><h2>Phiên {session.id}</h2><StatusBadge value={session.status}/>{session.status==="OPEN"&&<form className="inline-form" onSubmit={scan}><FormField label="Quét mã bản sao"><input value={barcode} onChange={e=>setBarcode(e.target.value)}/></FormField><button>Ghi nhận</button><button type="button" className="button-secondary" onClick={()=>void complete()}>Chốt kiểm kê</button></form>}<ul className="compact-list">{scans.map(x=><li key={x.copyId}>{x.barcode} — {x.type}</li>)}</ul></article>}</section>;
}
